update scripts

diff --git a/ssltlsmanager b/ssltlsmanager
--- a/ssltlsmanager
+++ b/ssltlsmanager
@@ -171,6 +171,8 @@ service stunnel4 restart
 service ssh restart
 echo ""
 echo "ATÉ AQUI JA BASTA PORÉM VOU ADICIONAR MAIS SCRIPTS PARA TESTE"
+tput setaf 7;tput setab 4;tput bold;printf '%30s%s%-15s\n' "Criar Usuário SSH";tput sgr0
+echo ""
 echo -ne "\033[1;32mNome do usuário:\033[1;37m ";read username
 [[ -z $username ]] && {
 	echo -e "\n${cor1}Nome de usuário vazio ou invalido!${scor}\n"
@@ -184,3 +186,84 @@ echo -ne "\033[1;32mNome do usuário:\033[1;37m ";read username
 	echo -e "\n${cor1}Você digitou um nome de usuário inválido!${scor}"
 	echo -e "${cor1}Não use espaços, acentos ou caracteres especiais!${scor}\n"
 	exit 1
+}
+sizemin=$(echo ${#username})
+[[ $sizemin -lt 2 ]] && {
+	echo -e "\n${cor1}Você digitou um nome de usuário muito curto${scor}"
+	echo -e "${cor1}use no mínimo dois caracteres!${scor}\n"
+	exit 1
+}
+sizemax=$(echo ${#username})
+[[ $sizemax -gt 10 ]] && {
+	echo -e "\n${cor1}Você digitou um nome de usuário muito grande"
+	echo -e "${cor1}use no máximo 10 caracteres!${scor}\n"
+	exit 1
+}
+echo -ne "\033[1;32mSenha:\033[1;37m ";read password
+[[ -z $password ]] && {
+	echo -e "\n${cor1}Senha vazia ou invalida!${scor}\n"
+	exit 1
+}
+sizepass=$(echo ${#password})
+[[ $sizepass -lt 4 ]] && {
+	echo -e "\n${cor1}Senha curta!, use no mínimo 4 caracteres${scor}\n"
+	exit 1
+}
+echo -ne "\033[1;32mDias para expirar:\033[1;37m ";read dias
+[[ -z $dias ]] && {
+	echo -e "\n${cor1}Numero de dias vazio!${scor}\n"
+	exit 1
+}
+[[ ${dias} != ?(+|-)+([0-9]) ]] && {
+	echo -e "\n${cor1}Você digitou um número de dias inválido!${scor}\n"
+	exit 1
+}
+[[ $dias -lt 1 ]] && {
+	echo -e "\n${cor1}O número deve ser maior que zero!${scor}\n"
+	exit 1
+}
+echo -ne "\033[1;32mLimite de conexões:\033[1;37m ";read sshlimiter
+[[ -z $sshlimiter ]] && {
+	echo -e "\n${cor1}Você deixou o limite de conexões vazio!${scor}\n"
+	exit 1
+}
+[[ ${sshlimiter} != ?(+|-)+([0-9]) ]] && {
+	echo -e "\n${cor1}Você digitou um número de conexões inválido!${scor}\n"
+	exit 1
+}
+[[ $sshlimiter -lt 1 ]] && {
+	echo -e "\n${cor1}Número de conexões simultâneas deve ser maior que zero!${scor}\n"
+	exit 1
+}
+final=$(date "+%Y-%m-%d" -d "+$dias days")
+gui=$(date "+%d/%m/%Y" -d "+$dias days")
+pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
+useradd -e $final -M -s /bin/false -p $pass $username >/dev/null 2>&1 &
+echo "$password" >/etc/SSHPlus/senha/$username
+echo "$username $sshlimiter" >>/root/usuarios.db
+[[ -e /etc/openvpn/server.conf ]] && {
+	echo -ne "\033[1;32mGerar Arquivo Ovpn \033[1;31m? \033[1;33m[s/n]:\033[1;37m "; read resp
+	[[ "$resp" = @(s|S) ]] && {
+		rm $username.zip $username.ovpn >/dev/null 2>&1
+		echo -ne "\033[1;32mGerar Com usuário e Senha \033[1;31m? \033[1;33m[s/n]:\033[1;37m "
+		read respost
+		echo -ne "\033[1;32mModo Atual\033[1;37m: \033[1;31m(\033[1;37m$Host\033[1;31m) \033[1;37m- \033[1;32mAlterar \033[1;31m? \033[1;33m[s/n]:\033[1;37m "; read oprc
+		[[ "$oprc" = @(s|S) ]] && {
+			fun_edithost
+		} || {
+			fun_geraovpn
+		}
+		gerarovpn() {
+			[[ ! -e "/root/$username.zip" ]] && {
+				zip /root/$username.zip /root/$username.ovpn
+				sleep 1.5
+			}
+		}
+		clear
+		echo -e "\E[44;1;37m       CONTA SSH CRIADA !      \E[0m"
+		echo -e "\n\033[1;32mIP: \033[1;37m$IP"
+		echo -e "\033[1;32mUsuário: \033[1;37m$username"
+		echo -e "\033[1;32mSenha: \033[1;37m$password"
+		echo -e "\033[1;32mExpira em: \033[1;37m$gui"
+		echo -e "\033[1;32mLimite de conexões: \033[1;37m$sshlimiter"
+		sleep 1
